version: "3.7"

services:

  nginx:
    container_name: relax_nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/app
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    networks:
      - "backend_network"

  php-fpm:
    container_name: relax_php-fpm
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/var/www/app
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    networks:
      - "backend_network"

  postgres:
    container_name: relax_postgres
    image: postgres:14.2
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data/pgdata:rw
      - ./:/var/www:ro
    ports:
      - "5432:5432"
    networks:
      - "backend_network"

  phppgadmin:
    container_name: relax_phppgadmin
    image: neimheadh/phppgadmin:latest
    ports:
      - "8080:80" # web browsers block the port 100080. Use 8080 instead.
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=default
      - POSTGRES_PASS=default
    networks:
        - "backend_network"

networks:
  backend_network:
    driver: bridge
